name: tasky
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  get_it: ^7.7.0
  go_router: ^14.1.4
  jwt_decoder: ^2.0.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.5
  intl_phone_number_input: ^0.7.4
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  mobile_scanner: ^5.1.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  phone_form_field: ^9.2.5
  buttons_tabbar: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#5F33E1"
  background_image: "assets/images/splash_logo.png"


  android_12:
    image: assets/images/splash_logo.png
    color: "#5F33E1"
    #icon_background_color: "#5F33E1"

  web: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Regular.ttf

